export const LATEST_VIDEOS_INITIALIZE = "LATEST_VIDEO_INITIALIZE";
export const LATEST_VIDEO_SUCCESS = "LATEST_VIDEO_SUCCESS";
export const LATEST_VIDEO_FAILED = "LATEST_VIDEO_FAILED";

export const LIKED_VIDEO_INITIALIZE = "LIKED_VIDEO_INITIALIZE";
export const LIKED_VIDEO_SUCCESS = "LIKED_VIDEO_SUCCESS";
export const LIKED_VIDEO_FAILED = "LIKED_VIDEO_FAILED";
export const GET_LIKED_VIDEO_SUCCESS = "GET_LIKED_VIDEO_SUCCESS";
export const GET_LIKED_VIDEO_FAILED = "GET_LIKED_VIDEO_FAILED";
export const DELETE_LIKED_VIDEO_SUCCESS = "DELETE_LIKED_VIDEO_SUCCESS";
export const DELETE_LIKED_VIDEO_FAILED = "DELETE_LIKED_VIDEO_FAILED";

export const PLAYLIST_INITIALIZE = "PLAYLIST_INITIALIZE";
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS";
export const ADD_PLAYLIST_SUCCESS = "ADD_PLAYLIST_SUCCESS";
export const GET_PLAYLIST_FAILED = "GET_PLAYLIST_FAILED";
export const ADD_PLAYLIST_FAILED = "GET_PLAYLIST_FAILED";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAILED = "DELETE_PLAYLIST_FAILED";

export const AUTH_INITIALIZE = "AUTH_INITIALIZE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
